stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: csp2-centos-1:5000/fiware-nifi:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      NIFI_WEB_HTTP_PORT: "7070"
    when:
      branch: {}
      event: {}
  - applyYamlConfig:
      path: ./service.yaml
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        echo Y | apt-get install npm
        npm -v
        sleep 300
        npm install -g newman
        newman run ./Draco.postman_collection.json
timeout: 60
branch:
  include:
  - master
notification: {}
