stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: draco-devops-image-new-test
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    envFrom:
    - sourceName: fiware-1921681001765000
      sourceKey: username
      targetKey: abc
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
timeout: 60
branch:
  include:
  - master
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
  - Changed
  - Failed
