stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: draco-devops-image-new-test
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: "apt-get update\napt-get install sshpass \n\n\n\n\n\n\n\n\n\nsshpass
        -p mehant ssh -tt -o StrictHostKeyChecking=no mehant@192.168.100.178 << EOF\n\n\n\ndir=`pwd`\n\necho
        \"Dir = ${dir}\"\n\npod_name=`kubectl --kubeconfig=config-176 get pods -n
        updateandrollback |grep \"api-test\" |cut -d \" \" -f1|head -n1`\n\necho \"Pod
        anme = ${pod_name}\"\n\n\nEOF\n"
timeout: 60
branch:
  include:
  - master
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
  - Changed
  - Failed
