stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: fiware-draco
      pushRemote: true
      registry: 192.168.100.176:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: aman.kumar1@india.nec.com
    notifier: c-h8ztd:n-kgmm2
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
  - Changed
  - Failed
