stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event:
        include:
        - pull_request
        - push
        - tag
timeout: 60
branch:
  include:
  - master
notification:
  recipients:
  - recipient: aman.kumar1@india.nec.com
    notifier: c-h8ztd:n-kgmm2
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
  - Changed
  - Failed
