stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: draco
      pushRemote: true
      registry: 192.168.100.178:5000
      env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker/2
timeout: 60
notification: {}
