stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: draco-devops-image-new
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch: {}
      event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      NIFI_WEB_HTTP_PORT: "7892"
    when:
      event: {}
timeout: 60
branch:
  include:
  - master
notification:
  recipients:
  - recipient: prabhat.upadhyay@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
  - Changed
  - Failed
