stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: nifi-ngsi-resources/docker/Dockerfile
      buildContext: .
      tag: draco-devops
      pushRemote: true
      registry: 192.168.100.178:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: aman.kumar1@india.nec.com
    notifier: c-h8ztd:n-kgmm2
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-8x5gc
  condition:
  - Success
