apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: draco
spec:
  replicas: 3
  template:
   metadata:
     labels:
       name: draco
   spec:
     containers:
     - name: draconifi
       image: csp2-centos-1:5000/draco=devops
       resources:
         limits:
          memory: "500Mi"
          cpu: "500m"
         requests:
          memory: "250Mi"
          cpu: "250m"
       ports:
       - containerPort: 9090
       - containerPort: 5050
       - containerPort: 6060
