apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: draco
  name: printig variable
  debug:
    var: CICD_EXECUTION_SEQUENCE
spec:
  replicas: 1
  template:
   metadata:
     labels:
       name: draco
   spec:
     containers:
     - name: draconifi
       image: 10.0.8.59:5000/testing-draco:$CICD_EXECUTION_SEQUENCE
       ports:
       - containerPort: 9090
       - containerPort: 5050
       - containerPort: 6060
---

apiVersion: v1
kind: Service
metadata:
  name: draco-service
  namespace: fiware
  labels:
    name: draco
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 31333
      name: data
    - port: 5050
      nodePort: 31344
      name: http
  selector:
    name: draco
