apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: draco
spec:
  replicas: 3
  template:
   metadata:
     labels:
       name: draco
   spec:
     containers:
     - name: draconifi
       image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
       ports:
       - containerPort: 9090
       - containerPort: 5050
       - containerPort: 7070
