apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fiware
  #namespace: test
  name: draco
spec:
  replicas: 3
  template:
   metadata:
     labels:
       name: draco
   spec:
     containers:
     - name: draconifi
       #image: 172.30.76.49:5000/draco:${CICD_EXECUTION_SEQUENCE}
       image: csp2-centos-1:5000/nifi_test_bare_2:${CICD_EXECUTION_SEQUENCE}
       resources:
         limits:
          memory: "1Gi"
          cpu: "1000m"
         requests:
          memory: "500Mi"
          cpu: "500m"
       ports:
       - containerPort: 9090
       - containerPort: 5050
       - containerPort: 6060

