apiVersion: v1
kind: Service
metadata:
  namespace: fiware
  #namespace: test
  name: draco-service
  labels:
    name: draco
spec:
  type: NodePort
  ports:
    - port: 9090
      #nodePort: 30007
      nodeport: 40190
      name: http
  selector:
    name: draco
